### ISSUE TITLE
Find a keybind for opening the menu other than ctrl-c that doesn't break everything else

### ISSUE THREAD

**Issue by SharpBit** [CupOfGeo/adaptable-antelopes#11]
Currently, clicking Ctrl-C opens the menu then clicking it again closes it, but ideally ctrl-c would be used for copying highlighted text.

I tried Ctrl-M but that's an alias for `Enter` so it doesn't really work. I tried another random keybind of Ctrl-K but `Enter` still breaks the application so we need to figure out if we want a copy command or find a way to fix this.

**Comment by BoraxTheClean** [comment]
> ... ideally ctrl-c would be used for copying highlighted text.

I've never used a TUI that supports highlighting text and copy/paste workflows. But it does definitely seem like something we want.

**Comment by BoraxTheClean** [comment]
> I tried Ctrl-M but that's an alias for `Enter` so it doesn't really work. I tried another random keybind of Ctrl-K but `Enter` still breaks the application so we need to figure out if we want a copy command or find a way to fix this.

Ctrl-M works for me on osx. Are you having this alias issue on Windows?
