### ISSUE TITLE
Marker/symbol to show if file is saved or not

### ISSUE THREAD

**Issue by SharpBit** [CupOfGeo/adaptable-antelopes#12]
- When a file is not yet saved, show an asterisk `*` in the title bar of the terminal
- Make it disappear when saving the file
- Needs an event that is called whenever the `TextArea` has its contents edited.

**Comment by ryan-heslin** [comment]
One of the basic examples shows how to do this for a fixed string, but triggering it dynamically on changes to the input text would be hard. TextArea has an accept_handler callable that's called when Enter is pressed, but that's not really complete solution.

https://github.com/prompt-toolkit/python-prompt-toolkit/blob/master/examples/prompts/terminal-title.py

**Comment by SharpBit** [comment]
Tried using `os.system` to modify the title bar but got `text_editor.py:72:1: S605 Starting a process with a shell, possible injection detected, security issue.` when linting.

Seems to be no event that is called whenever a `TextArea` has its contents edited.
There is `accept_handler – Called when Enter is pressed (This should be a callable that takes a buffer as input).` but that's only when Enter is pressed.

Maybe look into [History](https://python-prompt-toolkit.readthedocs.io/en/master/pages/reference.html?highlight=textarea#prompt_toolkit.history.History)

**Comment by ghost** [comment]
Just noticed the Buffer data structure has an `on_text_changed` callable, which sounds like what we're after.
https://python-prompt-toolkit.readthedocs.io/en/master/pages/reference.html#module-prompt_toolkit.buffer

**Comment by ghost** [comment]
I think this is definitely doable by setting that callable to toggle an asterisk before the window title on a change to the text buffer. I could then write a function to remove the asterisk on saving and call it from within each of the save functions on successful save.
