### ISSUE TITLE
mock a folder for scroll menu and read file names

### ISSUE THREAD

**Issue by CupOfGeo** [CupOfGeo/adaptable-antelopes#17]

**Comment by BoraxTheClean** [comment]
Related question: It looks like `scroll_menu.py` is unused and you made a class for the scroll menu in `text_editor.py`.

If that is correct, we should abstract the `ScrollMenuDialog` class into it's own namespace as part of this task.

**Comment by CupOfGeo** [comment]
Yeah i was thinking it would be a mock folder with fake files to for the scroll menu to pull names from to display and select.

**Comment by BoraxTheClean** [comment]
We should probably spec out what the expected behavior is before mocking it. Maybe you should take this task if you have a solid vision of what needs to be done.

**Comment by ntdkhiem** [comment]
I think this issue has been solved per my [PR](https://github.com/BoraxTheClean/adaptable-antelopes/pull/24) so it should be safe to close it.
