### ISSUE TITLE
Add Markdown Rendering

### ISSUE THREAD

**Issue by BoraxTheClean** [CupOfGeo/adaptable-antelopes#28]
There might be a prompt kit module or setting to enable this.

Removing line numbers is a + too.

**Comment by ntdkhiem** [comment]
Solved! https://github.com/BoraxTheClean/adaptable-antelopes/commit/1b86557f260d557b5f736f3dfd0af108eae9a1ae

The setting, by default, will not have any formatting until we open a file with correct extension.

In https://github.com/BoraxTheClean/adaptable-antelopes/blob/1b86557f260d557b5f736f3dfd0af108eae9a1ae/src/text/text_editor.py#L68-L72, You can change ".txt" to ".md" to verify it.

**Comment by ntdkhiem** [comment]
Wait, I might misunderstood this issue. I will wait for your clarification.

**Comment by ntdkhiem** [comment]
Solved! https://github.com/BoraxTheClean/adaptable-antelopes/pull/33
