### ISSUE TITLE
⬆️ move up on directory button in menu

### ISSUE THREAD

**Issue by CupOfGeo** [CupOfGeo/adaptable-antelopes#29]
From @CupOfGeo: We also need an ⬆️ move up on directory button for this use case.

_Originally posted by @BoraxTheClean in https://github.com/BoraxTheClean/adaptable-antelopes/pull/24#r667552001_

**Comment by ntdkhiem** [comment]
Solved! commit [ae8a8be274ec0c3a0bab8f70e6ca07fe3076cd84](https://github.com/BoraxTheClean/adaptable-antelopes/commit/ae8a8be274ec0c3a0bab8f70e6ca07fe3076cd84)
