### ISSUE TITLE
Save files to a notes directory additionally open to that directory

### ISSUE THREAD

**Issue by CupOfGeo** [CupOfGeo/adaptable-antelopes#35]
We should limit what folder and files it can access 

it should only be allowed into a main notes folder that you can go into and save notes there. This will also then need a way to make new folder and move files into them so its kind of a slippery slope

Maybe we just make it open .txt and .md files or a certain extension 

this should be done so at least you can edit its own code and save over it or anything.

**Comment by BoraxTheClean** [comment]
@CupOfGeo @ntdkhiem So the first time I open the app, it should look for a directory with a specific name say `.thought_box`, and if it doesn't find that, it will create it. When using the scroll menu, it should only be able to navigate inside `.thought_box` and it's subdirectories, not "break out" to directoires above `.thought_box`.

Does that sound right? Is there anything else you'd add?

**Comment by ntdkhiem** [comment]
ok sure, and the app should only able to open .txt and .md

**Comment by ghost** [comment]
So an error should be thrown on attempting to open a file with any other extension?

**Comment by ntdkhiem** [comment]
https://github.com/BoraxTheClean/adaptable-antelopes/commit/83ea15899bcf1a9617b12ce70df21461a0e48743
