### ISSUE TITLE
Make `get_status_bar_left_text` show a shortcuts menu

### ISSUE THREAD

**Issue by SharpBit** [CupOfGeo/adaptable-antelopes#41]
Instead of showing the name of the current file, make it clickable and show the shortcuts menu using a `MessageDialog`

**Comment by BoraxTheClean** [comment]
> Instead of showing the name of the current file, make it clickable and show the shortcuts menu

Do we have a shortcuts menu? Do you mean a popup that would show all the different hotkeys you can use in the app?

**Comment by SharpBit** [comment]
> Do you mean a popup that would show all the different hotkeys you can use in the app?

Yep

**Comment by SharpBit** [comment]
done in #90
