### ISSUE TITLE
Folders/make it feel like a notes app

### ISSUE THREAD

**Issue by SharpBit** [CupOfGeo/adaptable-antelopes#42]
- [x] Make it so ur only allowed to create and edit notes that are inside `.thought_box`
- Add the functionality to create/edit/delete folders (#66)
- Add the functionality to move and delete notes. (#67)

Enhancement:
- make it so you can move subfolders within the thoughtbox, to other folders (#68)

Folders should not be able to be named `.thought_box`

**Comment by BoraxTheClean** [comment]
I did a bit of this here https://github.com/BoraxTheClean/adaptable-antelopes/pull/47

We don't currently have a `delete` functionality. That should be its own issue.
> Also probably should be able to move notes between folders.

This should be its own issue.
> Folders should not be able to be named .thought_box

We should add some validation to folder names, but I feel like they can largely name it whatever they want.

**Comment by SharpBit** [comment]
Closed, moved to separate issues (#66, #67, #68)
