### ISSUE TITLE
Refactor text_editor.py

### ISSUE THREAD

**Issue by BoraxTheClean** [CupOfGeo/adaptable-antelopes#43]
**Is your feature request related to a problem? Please describe.**
We have way too many global variables and different pieces of code mutating the state of objects in text_edtior.

**Describe the solution you'd like**
We need a class that is the middleware between text_editor and other components wanting to change the state of text_editor. We potentially need the same for the application as a whole.

**Describe alternatives you've considered**
We are being judged on code quality, so this mattress 🛏️ 

**Additional context**
Don't be afraid to nit pick at code quality in code reviews.

**Comment by ntdkhiem** [comment]
https://github.com/BoraxTheClean/adaptable-antelopes/commit/f59f5df55ae989c7fde45d0ff74612a9b059c0cd
