### ISSUE TITLE
do_save_as_file not saving

### ISSUE THREAD

**Issue by ghost** [CupOfGeo/adaptable-antelopes#54]
I've been unable to save a file to a user-specified path. I think the problem is among the conditions of the `if` block in `do_save_as_file`.  Line 132 is:

```
and os.path.isfile(user_entered_path)
```
but the `os.path` documentation says `isfile` checks if a path _exists_, so I believe it's failing on valid paths that don't point to a file. 

I don't see an easy fix, but [this](https://stackoverflow.com/questions/9532499/check-whether-a-path-is-valid-in-python-without-creating-a-file-at-the-paths-ta) might be useful.

**Comment by CupOfGeo** [comment]
just comment it out for now and but maybe join it with application states.current_path

**Comment by BoraxTheClean** [comment]
This seems to be fixed, do we want to close?
