### ISSUE TITLE
Start the Application View

### ISSUE THREAD

**Issue by BoraxTheClean** [CupOfGeo/adaptable-antelopes#6]
From @CupOfGeo:
> As far as when starting it depends. I think we might want it to be its own application where you don't run it in any particular folder or else its just a word processor and that it should have its own folder with files you made in the application. maybe it can just load the last note you were working on or just make you a new note?
> https://discord.com/channels/862090812745318450/862090813211410491/863801028797661184

When the application loads it will load into the text editor screen. From there it will either start a new note, or load the most recently worked on note.

Since we are loading into the text editor UI, the scope of this issue is more about storing and restoring application state on application load, writing a file (update, delete, save), and application close.

**Comment by CupOfGeo** [comment]
we could maybe have a little pickle of last file name and maybe we can make other user prefs too

**Comment by BoraxTheClean** [comment]
Yep I think storing a pickle of application configuration in a hidden file in the application directory is a good pattern for this.

We can just start with storing the last opened file for now and add+migrate user preferences as we go.
