### ISSUE TITLE
How are Files Saved?

### ISSUE THREAD

**Issue by BoraxTheClean** [CupOfGeo/adaptable-antelopes#7]
# Decision Point
We need to decide if we are going to save files as normal `*.txt` files that contain only unicode characters and are rendered as such with no additional formatting.

Alternatively we could choose to treat every file as markdown (or similar), implementing our own selection of the markdown interface and rendering.

# Tradeoffs
The primary tradeoff at hand here is sacrificing compatibility with other text editors. If we only use `*.txt` files, notes can be opened and modified anywhere, but we sacrifice out of the box functionality in our application. 

If we go the markdown route, we can have ✨ pretty ✨ notes in our editor, but those notes opened elsewhere, will not render with the same formatting and might look garbled.

**Comment by BoraxTheClean** [comment]
It sounds like we're most interested in saving things in our own format and not caring about cross compatibility of `.txt` files.

Figma prototype of markdown rendering: https://www.figma.com/proto/aS5y6DFK1tPV3IAdNKCk1m/ThoughtBox-Text-Rendering?page-id=0%3A1&node-id=2%3A2&viewport=489%2C327%2C0.7621527910232544&scaling=min-zoom

**Comment by CupOfGeo** [comment]
i think for now just focus on getting it working for regular txt files. Even if we make our own extension its still gonna be a text file but with markup in it that you wont see when opening thought the application.

**Comment by CupOfGeo** [comment]
i was thinking files would be saved to a folder in the repo why i think we should have a mock #17

**Comment by BoraxTheClean** [comment]
> i was thinking files would be saved to a folder in the repo why i think we should have a mock #17

That sounds good. We just need to spec out exactly how we want it to work.
