### ISSUE TITLE
Stuff to do before the code jam ends:

### ISSUE THREAD

**Issue by SharpBit** [CupOfGeo/adaptable-antelopes#84]
- [x] check for spelling/grammar/formatting mistakes in the readme/docstrings
- [x] remove any comments that aren't describing the code
- [x] do any TODO comments
- [x] make sure everything works on every OS

**Comment by BoraxTheClean** [comment]
> * [ ]  do any TODO comments
> *

```bash
➜  adaptable-antelopes git:(main) grep todo src -i -r
```
Should we make this done?

**Comment by ntdkhiem** [comment]
> * [ ]  make sure everything works on every OS

App works for me (Windows).

**Comment by SharpBit** [comment]
> > * [ ]   make sure everything works on every OS
> 
> App works for me (Windows).

![image](https://user-images.githubusercontent.com/31069084/126017626-d0b28820-89be-4eb7-b2c7-6c5da909ead3.png)
does this still occur to you? @ntdkhiem

**Comment by ntdkhiem** [comment]
> > > * [ ]    make sure everything works on every OS
> > 
> > 
> > App works for me (Windows).
> 
> ![image](https://user-images.githubusercontent.com/31069084/126017626-d0b28820-89be-4eb7-b2c7-6c5da909ead3.png)
> does this still occur to you? @ntdkhiem

yeah...

**Comment by rishigian** [comment]
> > > > * [ ]     make sure everything works on every OS
> > > 
> > > 
> > > App works for me (Windows).
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/31069084/126017626-d0b28820-89be-4eb7-b2c7-6c5da909ead3.png)
> > does this still occur to you? @ntdkhiem
> 
> yeah...

What text did you write? I would like to see if it messes up my text to.

**Comment by rishigian** [comment]
Btw the app seems to work fine for me (mac)

**Comment by ntdkhiem** [comment]
> > > > * [ ]     make sure everything works on every OS
> > > 
> > > 
> > > App works for me (Windows).
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/31069084/126017626-d0b28820-89be-4eb7-b2c7-6c5da909ead3.png)
> > does this still occur to you? @ntdkhiem
> 
> yeah...

Actually, if you add a single space at the beginning of that line, everything somehow fixed.

**Comment by SharpBit** [comment]
Which line? It still doesn't work for me

![image](https://user-images.githubusercontent.com/31069084/126037350-8e656b71-9119-4546-929d-0d6c94b35b6f.png)

**Comment by ntdkhiem** [comment]
> Which line? It still doesn't work for me
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/31069084/126037350-8e656b71-9119-4546-929d-0d6c94b35b6f.png)
> 
> 

try using powershell instead

**Comment by SharpBit** [comment]
![image](https://user-images.githubusercontent.com/31069084/126042176-d79d0401-74b8-46cd-b4df-502a733f0df8.png)
still doesnt work

**Comment by BoraxTheClean** [comment]
What is the emoji bug? Should I try to fix it in the next hour?

**Comment by SharpBit** [comment]
![image](https://user-images.githubusercontent.com/31069084/126042217-5ab4aae3-76c4-4c57-bb47-503086b6a5e9.png)
looks like this. it messes up the text around it

**Comment by SharpBit** [comment]
I think it only happens on windows, not sure tho

**Comment by ntdkhiem** [comment]
try adding a space at the beginning of the line that has messed up text.

**Comment by BoraxTheClean** [comment]
Is it only happening on terminals that don't support unicode? Or does your terminal support unicode but it is just still broken?

**Comment by ntdkhiem** [comment]
Mine has emoji but the same messed up text. You can fix it somehow by adding any character at the beginning of the text.

**Comment by ntdkhiem** [comment]
Ah I see the problem with emoji now. I used Windows Terminal which has emoji unicode, but CMD and Powershell don't.
