### ISSUE TITLE
Show Selected directory when picking files and folders

### ISSUE THREAD

**Issue by CupOfGeo** [CupOfGeo/adaptable-antelopes#85]
wondering if we can show what the selected on the left side of the scroll which would be done in ScrollMenuDialog

_Originally posted by @CupOfGeo in https://github.com/BoraxTheClean/adaptable-antelopes/pull/82#discussion_r671503870_

**Comment by SharpBit** [comment]
![image](https://user-images.githubusercontent.com/31069084/126007957-90263154-cf96-44a8-9a10-ba6c0eaff785.png)
Yep, that's what I was thinking too

**Comment by SharpBit** [comment]
It would also simultaneously fix #64
