### ISSUE TITLE
if you backspace too much in a TextArea, some characters and the title bar show up

### ISSUE THREAD

**Issue by SharpBit** [CupOfGeo/adaptable-antelopes#91]
![image](https://user-images.githubusercontent.com/31069084/126038141-59b91483-a559-44b9-a7c9-555659da3a74.png)

**Comment by ntdkhiem** [comment]
Doesn't show it on my Windows.

**Comment by BoraxTheClean** [comment]
I am unable to reproduce. Ca you describe how I can reproduce this bug? @SharpBit

**Comment by SharpBit** [comment]
apparently only on command prompt, problem with library, unfixable
